name: DEV-CI
run-name: DEV-CI initiated by @${{ github.actor }}

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
    
    - name: Install packages
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: install

    - name: Run tests
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: test

    - name: Build the project
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: build
    
    - name: Compress build artifacts
      env:
        COMMIT_AUTHOR: ${{ github.actor }}
      run: |
        DATE=$(date +%Y%m%d_%H%M%S)
        FILENAME="build_${DATE}_${COMMIT_AUTHOR}.tar.gz"
        tar -czvf $FILENAME build/
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV

    - name: Upload build artifact to S3
      run: |
        aws s3 cp ${{ env.FILENAME }} s3://fup0414.artifactrepo/artifacts/${{ env.FILENAME}}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS }}
        AWS_DEFAULT_REGION: us-east-1