name: DEV-CD
run-name: Deploy initiated by ${{ github.actor }}

on:
  workflow_run:
    workflows: ["DEV-CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Get build artifact name
      run: |
        COMMIT_AUTHOR=${{ github.event.workflow_run.head_commit.author.username }}
        COMMIT_TIMESTAMP=${{ github.event.workflow_run.head_commit.timestamp }}
        DATE=$(date -u -d "$COMMIT_TIMESTAMP" +%Y%m%d_%H%M%S)
        FILENAME="build_${DATE}_${COMMIT_AUTHOR}.tar.gz"
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
    
    - name: Download build artifact from s3
      run: aws s3 cp s3://fup0414.artifactrepo/artifacts/${{ env.FILENAME }} ${{ env.FILENAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Uncompress build artifacts
      run: tar -xzvf ${{ env.FILENAME }}

    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        scripts: |
          sudo systemctl stop nginx
          rm -rf /var/www/html/*
          cp -r build/* /var/www/html/
          sudo systemctl start nginx