name: DEV-CD
run-name: Deploy initiated by ${{ github.actor }}

on:
  workflow_run:
    workflows: ["DEV-CI"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Get the latest build artifact
      run: |
        LATEST_OBJECT=$(aws s3api list-objects-v2 \
          --bucket fup0414.artifactrepo \
          --prefix artifacts/ \
          --query 'Contents[?Size>`0`].[Key, LastModified]' \
          --output json | jq -r 'sort_by(.[1]) | reverse | .[0][0]' | head -1)
        echo "LATEST_OBJECT=$LATEST_OBJECT" >> $GITHUB_ENV
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS }}
        AWS_DEFAULT_REGION: us-east-1
      
    - name: Download build artifact from s3
      run: aws s3 cp s3://fup0414.artifactrepo/${{ env.LATEST_OBJECT }} ${{ env.LATEST_OBJECT }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Uncompress build artifacts
      run: |
        tar -xzvf ${{ env.LATEST_OBJECT }}

    - name: Deploy to EC2 instance
      uses: easingthemes/ssh-deploy@v4.1.8
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "./build"
        TARGET: "/var/www/html"
        SCRIPT_BEFORE: |
          sudo systemctl stop nginx
          sudo rm -rf /var/www/html/*
        SCRIPT_AFTER: |
          sudo systemctl start nginx
          echo $RSYNC_STDOUT